# -*- coding: utf-8 -*-
"""VedabaseBS4.ipynb

Automatically generated by Colaboratory.
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

df = pd.DataFrame(columns=["id","san","eng"])

for canto in range(1,13):
  canto_page = requests.get("https://vedabase.io/en/library/sb/"+str(canto))
  canto_soup = BeautifulSoup(canto_page.content, 'html.parser')
  chapters = canto_soup.select("div.r-chapter a")
  for chapter in chapters:
    if (chapter.get("href").split('/')[-2].isnumeric()):
      chap_page = requests.get("https://vedabase.io"+chapter.get("href")+"advanced-view")
      chap_soup = BeautifulSoup(chap_page.content, 'html.parser')
      texts = chap_soup.select("div.bb.r-verse h1 a")
      for text in texts:
        text_page = requests.get("https://vedabase.io"+text.get("href"))
        text_soup = BeautifulSoup(text_page.content, 'html.parser')
        para = text_soup.select("div.wrapper-verse-text")[0]

        sans = ""
        for div in para.findChildren("div"):
          sans += " "+div.get_text()
        
        english = text_soup.select("div.r.r-lang-en.r-translation p")[0].get_text()
        print(text.get("href")[15:])
        df.loc[len(df)]=[text.get("href")[15:],sans,english]

df.to_csv('output.csv',index=False)